name: Supabase Workers (Hourly)

on:
  #schedule:
  #  - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run-workers:
    runs-on: ubuntu-latest
    timeout-minutes: 70

    strategy:
        fail-fast: false matrix: 
        include: 
            - worker: 1 
              url: https://lezrsmwspvrdahngtvli.supabase.co/functions/v1/PojectSend 
            - worker: 2 
              url: https://vuudkapcuwtkepeqkpfx.supabase.co/functions/v1/PojectSend
            - worker: 3 
              url: https://guypgtlqmsoyjvsspfro.supabase.co/functions/v1/PojectSend
            - worker: 4 
              url: https://neighiwqhabqzhakwupe.supabase.co/functions/v1/PojectSend
            - worker: 5 
              url: https://gmweskylxvbhhgrcftbo.supabase.co/functions/v1/PojectSend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          pip install requests

      - name: Run worker
        run: python -u script.py
        env:
          WORKER_ID: worker${{ matrix.worker }}
          URL: ${{ matrix.url }}
